# Generated by Django 5.1 on 2024-08-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0003_platof_postre_rename_product_bebida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('descripcion', models.CharField(default='', max_length=400)),
                ('img', models.URLField()),
            ],
        ),
    ]
